### ISSUE TITLE
Clipping occurs sometimes

### ISSUE THREAD

**Issue by mnordine** [bp74/StageXL#277] opened 2017-05-30 14:23 UTC
There's certainly an issue where sometimes DisplayObjects get clipped. It's as if the width and height properties are not correct.  This must have happened very recently. I'm going to try to give you an minimal case soon.

**Comment by bp74** [comment] 2017-06-08 06:03
Just a quick update on this issue. I know what causes the trouble. It's the optimized rectangle mask in StageXL 1.2 which uses the WebGL scissors instead of the stencil buffer. The problem is that the cached display object also applies the scissors to the texture of the cache. I still need to get my head around how to fix this, but at least i know what is going on. I will keep you posted.

**Comment by bp74** [comment] 2017-06-08 06:41
Fixed with this commit: f1194804c40819026965075c790f1a57cc19e5f8

Fix released with StageXL 1.2.0+3

**Closed by bp74** 2017-06-08 06:41 UTC
