### ISSUE TITLE
Scaling the Sprite with tint filter is not shown correctly on mobile iOS browser

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#213] opened 2015-09-07 15:38 UTC
For recreating this bug check this on any iOS device

http://playpowerlabs.org/lwactivities/Cranach/

Select any screen
Add + sign
Under shapes category select any shape
Resize the shape by pinching (with two fingers)

It runs perfectly on the android browser

**Comment by bp74** [comment] 2015-09-07 21:53
Thanks for the bug report and the repro sample, i will take a look at it!

**Comment by bp74** [comment] 2015-09-08 11:50
It's really hard to get someone with an iPhone, everyone i know switched to Android :) My old iPhone 4 does not support WebGL, i will keep on searching ... Maybe you could show an screenshot that helps me to understand the problem.

**Comment by KakashiSensei** [comment] 2015-09-08 12:15
here is the video
share.shutterfly.com/action/welcome?sid=0AZN27Fw1ZtHLlw

First image is having the grey tint which cuts when scaled
and the second image of horse is the normal image without the tint

**Comment by bp74** [comment] 2015-09-08 12:32
Is this the WebGL renderer or do you use applyCache with the Canvas renderer?

**Comment by bp74** [comment] 2015-09-08 12:32
Let me ask in a different way? Do you use applyCache anywhere with the TintFilter?

**Comment by KakashiSensei** [comment] 2015-09-08 12:41
I use WebGL renderer and no apply cache is used
On Android Browser it works fine.

**Comment by bp74** [comment] 2015-09-08 16:50
Maybe you could try a simple work around for this issue. It looks like that iOS has an issue as soon as the texture get's bigger. You could try to apply the filter to the Bitmap which is not scaled, but the outer container (a Sprite) is scaled. This way the tinted version may be even rendered faster because there is no need to render it to a temporary (big) texture.

Old version:

    var sprite = new Sprite();
    var bitmap = new Bitmap(bitmapData);
    sprite.filter = [new TintFilter(Color.Gray)];
    spirte.addChild(bitmap);

New version:

    var sprite = new Sprite();
    var bitmap = new Bitmap(bitmapData);
    bitmap.filter = [new TintFilter(Color.Gray)];
    spirte.addChild(bitmap);

The second version is actually faster because the first version needs to render the content of the Sprite to a temporary textures (which probably causes the issue because you need a very big texture). The second version uses the TintFilter to render the pixels directly from the BitmapData to the screen.

Hope this helps, but of course i will try to find the cause for this issue.

**Comment by KakashiSensei** [comment] 2015-09-10 09:44
Yup the solution worked! Thanks a lot

**Comment by bp74** [comment] 2015-09-10 10:23
Great. I'm happy that we have a quick fix for the problem!

**Comment by bp74** [comment] 2015-12-05 18:42
I'm pretty sure this issue was caused by a limitation on the WebGL texture size on some devices. Best practice would be to avoid such big texture anyway. I will close this issue but if a problem like this happens again we will reopen it.

**Closed by bp74** 2015-12-05 18:42 UTC
Labels: under investigation
