### ISSUE TITLE
Sprite requires parent in order to be added to the display list?!

### ISSUE THREAD

**Issue by synthecypher** [bp74/StageXL#173] opened 2014-12-31 13:48 UTC
I'm trying to add a instance of a class which extends Sprite to the display list of a Stage instance.

However when I attempt to I always get a ```NoSuchMethodError: method not found: 'parent'``` This appears to happen on ```line:39``` of ```display_object_container.dart```.

```
if (child.parent == this) {
  _children.remove(child);
  if (index > _children.length) index -= 1;
  _children.insert(index, child);
  ...
```

Shouldn't this be checking to see if the method/property exists first before using it, as a ```Sprite``` that has not yet been added to a display list will have a ```parent``` of null?

**Comment by bp74** [comment] 2015-01-01 10:43
Yes as Nils says, the problem is probably the _game variable because it is null. The exception you get basically says "The null object has no property parent". Every object you add to the display list has to be an instance of a display object (like Sprite). You can't add a "null" to the display list.

**Comment by bp74** [comment] 2015-01-01 10:44
I will close this issue. If the answer from Nils and my answer don't help please reopen this issue.

**Closed by bp74** 2015-01-01 10:44 UTC
