### ISSUE TITLE
Alpha not working on bitmap with tint filter

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#194] opened 2015-05-18 01:46 UTC
I am trying to change the alpha of Bitmap on which tint filter is applied. It seems that with tint filter on bitmap no alpha property on bitmap is applied. I am using tint filter to apply color on bitmap font and want to change the alpha. I am using the dev version (0.12.0). I haven't checked in previous version.

Thanks

**Comment by bp74** [comment] 2015-05-18 05:00
Thanks for the bug report. I can see what the problem is. It is the pre-multiplied alpha thing with the tint color. It's an easy fix and I will commit the changes a little but later today.

**Comment by bp74** [comment] 2015-05-18 16:32
I fixed the issue with the TintFilter. Please do a quick test to see if it works as exepected. I did some tests too and i think it's correct now.

**Comment by bp74** [comment] 2015-06-22 18:02
Fixed in StageXL 0.12

**Closed by bp74** 2015-06-22 18:02 UTC
Labels: fixed - release pending, StageXL Bug
